# Generated by Django 4.2 on 2023-05-27 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produtos_vendas_delete_cliente_delete_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='dataUltimaVenda',
        ),
        migrations.AddField(
            model_name='vendas',
            name='dataVenda',
            field=models.DateField(auto_now=True, verbose_name='Data Venda'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='cpfcliente',
            field=models.CharField(max_length=200, verbose_name='CPF cliente'),
        ),
        migrations.CreateModel(
            name='ItemVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produtos')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendas')),
            ],
        ),
        migrations.AddField(
            model_name='vendas',
            name='itens',
            field=models.ManyToManyField(related_name='Produtos', through='core.ItemVendas', to='core.produtos', verbose_name='Produtos'),
        ),
    ]
