# Generated by Django 4.2 on 2023-05-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_produtos_dataultimacompra_remove_vendas_itens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='vendas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.vendas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='dataCompra',
            field=models.DateField(auto_now_add=True, verbose_name='Data Compra'),
        ),
    ]
