# Generated by Django 4.2 on 2023-05-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vendas_datavenda_itensvendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='valorVenda',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
