# Generated by Django 4.2 on 2023-05-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vendas_valorvenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendas',
            old_name='cpfcliente',
            new_name='cpfCliente',
        ),
        migrations.AlterField(
            model_name='vendas',
            name='dataVenda',
            field=models.DateTimeField(verbose_name='Data Venda'),
        ),
    ]
