# Generated by Django 4.2 on 2023-05-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_cpfcliente_vendas_cpfcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensvendas',
            name='valorProdutoAplicado',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itensvendas',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produtos'),
        ),
        migrations.AlterField(
            model_name='itensvendas',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendas'),
        ),
    ]
