# Generated by Django 4.2 on 2023-05-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_itensvendas_valorprodutoaplicado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='cest',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='codBarras',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='codFabrica',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='cstcsosn',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='dataCompra',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='idGrade',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='ncm',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='precoCompra',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='situacaoFiscal',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='txRetorno',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='valorCusto',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='valorTotal',
        ),
    ]
