# Generated by Django 4.2 on 2023-05-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_vendas_valorvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='dataVenda',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Venda'),
        ),
    ]
