# Generated by Django 4.2 on 2023-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_itensvendas_valortotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensvendas',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itensvendas',
            name='valorProdutoAplicado',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Aplicado Unidade'),
        ),
        migrations.AlterField(
            model_name='itensvendas',
            name='valorTotal',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Total'),
        ),
    ]
